apiVersion: v1
kind: Secret
metadata:
  name: host-worker-credentials
  namespace: default
type: Opaque
data:
  username: SExNMDA2
  password: akM0SGh0M053  # jC4Hht3Nw
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: host-worker
  namespace: default
  labels:
    cluster-role: worker
spec:
  online: true
  bootMACAddress: 5c:b9:01:89:c2:90
  bmc:
    address: ilo4-virtualmedia://192.168.10.66
    disableCertificateVerification: true
    credentialsName: host-worker-credentials
