apiVersion: v1
kind: Secret
metadata:
  name: host-ctrl-credentials
  namespace: default
type: Opaque
data:
  username: SExNMDA2
  password: akM0SGh0M053  # jC4Hht3Nw
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: host-ctrl
  namespace: default
  labels:
    cluster-role: control-plane
spec:
  online: true
  bootMACAddress: 8c:dc:d4:16:58:90 # 1gb-port1
  bmc:
    address: ilo4-virtualmedia://192.168.9.153
    disableCertificateVerification: true
    credentialsName: host-ctrl-credentials
