apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3Cluster
metadata:
  name: sample-cluster
  namespace: default
spec:
  controlPlaneEndpoint:
    host: 192.168.75.100
    port: 6443
  noCloudProvider: true
---
apiVersion: ipam.metal3.io/v1alpha1
kind: IPPool
metadata:
  name: provisioning-pool
  namespace: default
spec:
  clusterName: sample-cluster
  namePrefix: sample-cluster-prov
  pools:
  - end: 192.168.75.200
    start: 192.168.75.100
  prefix: 24
---
apiVersion: ipam.metal3.io/v1alpha1
kind: IPPool
metadata:
  name: baremetalv4-pool
  namespace: default
spec:
  clusterName: sample-cluster
  gateway: 10.84.81.14
  namePrefix: sample-cluster-bmv4
  pools:
  - end: 10.84.81.11
    start: 10.84.81.9
  prefix: 24
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3DataTemplate
metadata:
  name: sample-cluster-controlplane-template
  namespace: default
spec:
  clusterName: sample-cluster
  metaData:
    ipAddressesFromIPPool:
    - key: provisioningIP
      name: provisioning-pool
    objectNames:
    - key: name
      object: machine
    - key: local-hostname
      object: machine
    - key: local_hostname
      object: machine
    prefixesFromIPPool:
    - key: provisioningCIDR
      name: provisioning-pool
  networkData:
    links:
      ethernets:
      - id: eth2
        macAddress:
          fromHostInterface: eth2
        type: phy
      vlans:
      - id: eth2.1076
        macAddress:
          fromHostInterface: eth2
        vlanID: 1076
        vlanLink: eth2
    networks:
      ipv4:
      - id: eth2
        ipAddressFromIPPool: provisioning-pool
        link: eth2
        routes:
        - gateway:
            string: 192.168.75.254
          network: 192.168.10.0
          prefix: 21
      - id: eth2.1076
        ipAddressFromIPPool: baremetalv4-pool
        link: eth2.1076
        routes:
        - gateway:
            fromIPPool: baremetalv4-pool
          network: 0.0.0.0
    services:
      dns:
      - 192.168.75.7
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3DataTemplate
metadata:
  name: sample-cluster-workers-template
  namespace: default
spec:
  clusterName: sample-cluster
  metaData:
    ipAddressesFromIPPool:
    - key: provisioningIP
      name: provisioning-pool
    objectNames:
    - key: name
      object: machine
    - key: local-hostname
      object: machine
    - key: local_hostname
      object: machine
    prefixesFromIPPool:
    - key: provisioningCIDR
      name: provisioning-pool
  networkData:
    links:
      ethernets:
      - id: eth4
        macAddress:
          fromHostInterface: eth4
        type: phy
      vlans:
      - id: eth4.1076
        macAddress:
          fromHostInterface: eth4
        vlanID: 1076
        vlanLink: eth4
    networks:
      ipv4:
      - id: eth4
        ipAddressFromIPPool: provisioning-pool
        link: eth4
        routes:
        - gateway:
            string: 192.168.75.254
          network: 192.168.10.0
          prefix: 21
      - id: eth4.1076
        ipAddressFromIPPool: baremetalv4-pool
        link: eth4.1076
        routes:
        - gateway:
            fromIPPool: baremetalv4-pool
          network: 0.0.0.0
    services:
      dns:
      - 192.168.75.7
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: sample-cluster-controlplane
  namespace: default
spec:
  template:
    spec:
      dataTemplate:
        name: sample-cluster-controlplane-template
      hostSelector:
        matchLabels:
          cluster-role: control-plane
      image:
        checksum: http://media.suse.baremetal/ubuntu_22.04-efi.qcow2.md5
        checksumType: md5
        format: qcow2
        url: http://media.suse.baremetal/ubuntu_22.04-efi.qcow2
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: sample-cluster
    nodepool: nodepool-0
  name: sample-cluster
  namespace: default
spec:
  clusterName: sample-cluster
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: sample-cluster
      nodepool: nodepool-0
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: sample-cluster
        nodepool: nodepool-0
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha1
          kind: RKE2ConfigTemplate
          name: sample-cluster-workers
      clusterName: sample-cluster
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: Metal3MachineTemplate
        name: sample-cluster-workers
      nodeDrainTimeout: 0s
      version: v1.25.3+rke2r1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: sample-cluster-workers
  namespace: default
spec:
  template:
    spec:
      dataTemplate:
        name: sample-cluster-workers-template
      hostSelector:
        matchLabels:
          cluster-role: worker
      image:
        checksum: http://media.suse.baremetal/ubuntu_22.04-efi.qcow2.md5
        checksumType: md5
        format: qcow2
        url: http://media.suse.baremetal/ubuntu_22.04-efi.qcow2